### PR TITLE
Fix import/export; hide private API

### PR DESCRIPTION
**Pull request by KonstantinRitt**

### CODE REVIEW

**Comment by mwallnoefer** [comment]
Very good work, Konstantin!

**Comment by wguynes** [comment]
The _p designation in the filename general refers to the PIMPL pattern, not to whether a given header file is exposed to the library user. It appears you've now confused these headers with true PIMPL private implementations with the rename.

**Comment by KonstantinRitt** [comment]
In Qt itself, all header files aimed to be a part of the private API would have _p suffix (well, with rare exceptions).

**Comment by KonstantinRitt** [comment]
Anyways, this is a preparation step for https://github.com/emqtt/qmqtt/pull/80/commits/fabfc76d47d8c69361cc245c1c7cab6d66922e22 , which makes the private API explicitly private

**Pull request merged**
