### PR TITLE
Long live to qmqtt Qt module!

### PR DESCRIPTION
**Pull request by KonstantinRitt**
Travis rules might need to be adjusted (sorry, I don't have too much experience with it)

### CODE REVIEW

**Comment by mwallnoefer** [comment]
This is also very good work.

@emqtt/qmqtt-team 
I am happy with this changes, do also the other maintainers agree that emqtt should become a Qt module?

**Comment by emqplus** [comment]
@KonstantinRitt Thanks for your work:) @mwallnoefer, I'd like to merge the PR.

**Comment by mwallnoefer** [comment]
@emqplus Thanks for your opinion.
@wguynes @wuming123057 Are you also fine with this PR?

If I hear nothing I would merge it tomorrow.

**Comment by wguynes** [comment]
I'm fine with it.

**Comment by KonstantinRitt** [comment]
Thanks

**Comment by mwallnoefer** [comment]
One thing which we need to look into is the breakage of the Android build process:

> 15:23:20: Starting: "C:\Qt\5.7\android_armv7\bin\androiddeployqt.exe" --input H:/Qt/build-qmqtt-Android_for_armeabi_v7a_GCC_4_9_Qt_5_7_0-Release/examples/mqtt/client/android-libqmqtt_example.so-deployment-settings.json --output H:/Qt/build-qmqtt-Android_for_armeabi_v7a_GCC_4_9_Qt_5_7_0-Release/android-build --deployment bundled --android-platform android-23 --jdk "C:/Program Files/Java/jdk1.8.0_102" --ant "C:/Program Files (x86)/apache-ant-1.9.6/bin/ant.bat"
> Cannot find application binary H:/Qt/build-qmqtt-Android_for_armeabi_v7a_GCC_4_9_Qt_5_7_0-Release/examples/mqtt/client/libqmqtt_example.so.
> 15:23:20: The process "C:\Qt\5.7\android_armv7\bin\androiddeployqt.exe" exited with code 2.
Error while building/deploying project qmqtt (kit: Android for armeabi-v7a (GCC 4.9, Qt 5.7.0))
When executing step "Build Android APK"

**Comment by KonstantinRitt** [comment]
That's a known issue with Qt for Android modules when building via QtCreator. The simplest one can do so far is disabling the "Build APK" step (it does nothing for TEMPLATE=lib but fails to detect the module build and thus tries to gather all shipped examples into the APK)

**Comment by KonstantinRitt** [comment]
Hi guys.
Is there any interest in moving this project to Qt Playground (see https://wiki.qt.io/Creating_a_new_module_or_tool_for_Qt for details)?
If so, I could help in promotion and further API polishing.

**Comment by mwallnoefer** [comment]
Nice idea!

**Pull request merged**
