### PR TITLE
Fix crash on non-existent hardcoded SSL cert

### PR DESCRIPTION
**Pull request by wiebeytec**

### CODE REVIEW

**Comment by mwallnoefer** [comment]
Fine for me, does anyone have objections?

**Comment by wiebeytec** [comment]
BTW, my patch was merely to fix the crash. The code itself is somewhat questionable. I don't think it's a good idea to load any certificate from whatever happens to be the current working directory.

Also, why is a key added as well? It's not a server, nor is SSL used as client certificate.

**Comment by mwallnoefer** [comment]
The key has been added by an external contribution c8ba2f48fd4b4956370c4d6164c0ecf19dfbb7e3 and was not there in the first place.

As you see the old code was simply:
```
    _socket->connectToHostEncrypted(hostName, port);
     if (!_socket->waitForEncrypted())
...
```

So would it be better to turn back to the old behaviour? Or how could we fix this best?

**Comment by wiebeytec** [comment]
At least with Mosquitto, you're kind of encouraged to have your own CA certificate, not a commercial one. You can see this in a tool like `mosquitto_sub`, which enables SSL with the `--cafile` option (it doesn't just load the system CAs). To that end, Qmqtt needs an API to be able to set the necessary parameters, which includes the CA file. This can then be set with something like `QSslSocket::addDefaultCaCertificates()` or ` sslConf.setLocalCertificate()`.

For complete compatibility, I would just like an extra method `addCAFile(QString path)`, and leave the constructor bool for SSL. It is then able to work with custom CAs or commercial ones.

Mqtt also supports client certificates. This involves the opposite of the above: the server needs to know the CA, and the client is given a key with certificate. I'm not sure about the required implementation, but it should be easy to find out. But this should be a separate issue, I think.

**Comment by ejvr** [comment]
What about allowing the user to pass a QSslConfiguration object to the constructor of the Client class, and pass it to the new QSslSocket using the setSslConfiguration function. 

This would allow the user of the client to set all available SSL parameters (including the ca-certificate).

If you want I can supply a patch to do this.

**Comment by mwallnoefer** [comment]
That's a great patch, thanks @ejvr for your hard work.

@emqtt/emqttd-dev-team Other opinions?

**Comment by emqplus** [comment]
@mwallnoefer Thanks, It's okay. I will assign the administrator of this project to you.

**Comment by mwallnoefer** [comment]
I merged the improvements done by @ejvr.

@wiebeytec I hope this is okay for you, otherwise please reopen and provide a follow-up patch.

**Comment by wiebeytec** [comment]
@ejvr's patch works very well for me.

**Pull request closed without merging**
