### PR TITLE
fix resource releases of member objects.

### PR DESCRIPTION
**Pull request by mwallnoefer**
A similar concept is used in http://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/io/qdatastream.cpp

### CODE REVIEW

**Comment by wguynes** [comment]
I'm unsure what this change is achieving.

QScopedPointer takes ownership of the network interface that is passed in on the constructor and ensures deletion.

**Comment by mwallnoefer** [comment]
I look at the constructor signatures of the classes `Client` and `Network`:

```
class QMQTTSHARED_EXPORT Client : public QObject
{
...
public:
    Client(const QHostAddress& host = QHostAddress::LocalHost,
           const quint16 port = 1883,
           QObject* parent = NULL);

    // for testing purposes only
    Client(NetworkInterface* network,
           const QHostAddress& host = QHostAddress::LocalHost,
           const quint16 port = 1883,
           QObject* parent = NULL);
...
```

```
class Network : public NetworkInterface
{
...
public:
    Network(QObject* parent = NULL);
    Network(SocketInterface* socketInterface, TimerInterface* timerInterface,
            QObject* parent = NULL);
...
```

This tells me that `NetworkInterface* network`, `SocketInterface* socketInterface` and `TimerInterface* timerInterface` may be created internally by `new` or provided externally as arguments. In the latter cases they could be stack-based objects but also heap ones, in any case the de-allocation is left to the caller.
In the first case as we have called `new`, we need also take care of calling `delete` (my changes to the destructors). Just using `QScopedPointers` would fix this, but how to do with the external objects?
To figure out the correct case I used the same technique as in Qt, the conditional `bool` flags in the destructors and removed the `QScopedPointers`.
Maybe a `QScopedPointer` with a custom deleter could approach the same...

**Comment by wguynes** [comment]
The only use-case of the dependency injection interface should be injecting a mock object for testing purposes. Protecting against double-deletion is unnecessary.
 
Production code generally shouldn't be supporting test code. If I could get away with eliminating the 2nd constructor entirely, I would. Unfortunately, interfaces are the only way to adequately support google mocking.

qmqtt_network.h will not be packaged in the qmqtt or qmqtt-dev package, so they won't be using either constructor, no need to protect them.

Naturally if we wish to allow our developers to inject their own network layer in the future, then this becomes a concern.

**Comment by mwallnoefer** [comment]
Okay for the first case, I understand your concerns.

Regarding the second case: wouldn't it then be better to match the first situation and convert `socketInterface` and `timerInterface` into QScopedPointers? Since currently they always leak when allocated internally. I understand that it is only about test cases, but a QScopedPointers seems not bad as the pointers are not exposed and external deletes cannot take place.

**Comment by wguynes** [comment]
In `QMQTT::Network::initialize()` function `_socket` and `_autoReconnectTimer` are parented the Network class.
```
    _socket->setParent(this);
    _autoReconnectTimer->setParent(this);
```
This will ensure deletion of these objects when Network's destructor is called.

I have no problem moving to a consistent technique. :) We could use either QScopedPointers or QObject parenting. I would go with QObject parenting if we have no objection with making the interfaces QObjects which is something I'm positive we can't avoid entirely since the interfaces must have the ability to send and receive signals.

**Comment by mwallnoefer** [comment]
Ah okay,  did not get the concept of the parentship.
I agree with you that a consistent technique would improve the code comprehension. Personally I am fine with either (parent or smart pointers) but your preference for QObject sounds reasonable.

**Pull request closed without merging**
