### PR TITLE
Tests changed, names changed to match

### PR DESCRIPTION
**Pull request by wguynes**
Just some test renaming

### CODE REVIEW

**Comment by mwallnoefer** [comment]
@wguynes Sorry, I merged in the Qt module patch so this one needs to be rebased :(.

**Comment by wguynes** [comment]
@mwallnoefer I have the rebase ready but we should hold off until the tests pass again. Currently broken.

**Comment by mwallnoefer** [comment]
@wguynes Any news here?

**Comment by mwallnoefer** [comment]
This has been open for a long time, so I close now. Please propose an eventual amendment.

**Pull request closed without merging**
